logger1:
    interval: 1 # minutes
    host: localhost
    port: 21
    username: dwpascal34
    password: scream123
    log-file-directory: /var/skyhook/logs
    log-file-name: logger1.log
    level: INFO

logger2:
    interval: 1 # minutes
    host: localhost
    port: 21
    username: dwpascal34
    password: scream123
    log-file-directory: /var/skyhook/logs
    log-file-name: logger2.log
    level: DEBUG